language: node_js
node_js:
  - 7
cache:
  yarn: true
env:
  global:
  - NODE_ENV=test
services:
- mongodb
- rabbitmq
- redis-server
install:
- pwd
- cd ./api && yarn install
- pwd
- cd ./worker && yarn install
- pwd
cache:
  directories:
    - ./api/node_modules
    - ./worker/node_modules
before_script:
- sleep 10
script:
- pwd
- cd ./api && yarn run test
- pwd
