language: node_js
node_js:
  - 7
services:
- mongodb
- rabbitmq
cache:
  yarn: true
  directories:
    - ./api/node_modules
    - ./worker/node_modules
env:
  global:
  - NODE_ENV=test
before_install:
- pwd && ls
- cp config api/config
- pwd && ls
- cp models api/src/models
- pwd && ls
- cp worker worker/config
- pwd && ls
- cp models api/src/models
- pwd && ls
install:
- cd ./api && npm install
- pwd && ls
- cd ../worker && npm install
- pwd && ls
- cd ../
- pwd && ls
before_script:
- sleep 10
- pwd && ls
script:
- pwd && ls
- cd ./api && npm test
- pwd && ls 
