version: '2'
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: hapi_rabbit
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 15672:15672
      - 5672:5672

  mongodb:
    image: mongo:3.0.2
    container_name: hapi_mongo
    restart: always
    ports:
      - 27017:27017

  api:
    build: ./api
    restart: always
    depends_on:
      - rabbitmq
      - mongodb
    ports:
      - 8000:8000
    environment:
      - NODE_ENV=development

  worker:
    build: ./worker
    # restart: always
    environment:
      - NODE_ENV=development
    depends_on:
      - rabbitmq
      - mongodb
