version: '2'
services:

  api:
    build: ./api
    container_name: hapi_api
    restart: always
    volumes:
      - "./api:/api"
      - "./config:/api/config"
      - "./models:/api/src/models"
      - "./queues:/api/src/queues"
    ports:
      - 8000:8000

  worker:
    build: ./worker
    container_name: hapi_worker
    volumes:
      - "./worker:/worker"
      - "./config:/worker/config"
      - "./models:/worker/src/models"
      - "./queues:/worker/src/queues"
