version: '2'
services:

  api:
    build: ./api
    container_name: hapi_api
    restart: always
    volumes:
      - "./api:/api"
      - "./config:/api/config"
    ports:
      - 8000:8000

  worker:
    build: ./worker
    container_name: hapi_worker
    volumes:
      - "./worker:/worker"
      - "./config:/worker/config"
