version: '2'
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: hapi_rabbit
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 15672:15672
      - 5672:5672

  mongodb:
    image: mongo:3.0.2
    container_name: hapi_mongo
    restart: always
    ports:
      - 27017:27017

  api:
    build: ./api
    container_name: hapi_api
    tty: true
    environment:
      - COMPOSE_HTTP_TIMEOUT=200
    volumes:
      - "./api:/api"
      - "./config:/api/config"
    restart: always
    # command: yarn run start
    depends_on:
      - rabbitmq
      - mongodb
    ports:
      - 8000:8000
    env_file:
      - ./config/env/test.env

  worker:
    build: ./worker
    container_name: hapi_worker
    tty: true
    environment:
      - COMPOSE_HTTP_TIMEOUT=200
    volumes:
      - "./worker:/worker"
      - "./config:/worker/config"
    # command: yarn run start
    # restart: always
    env_file:
      - ./config/env/test.env
    depends_on:
      - rabbitmq
      - mongodb
